---
# This task will provision AWS VPC with user inputs present in defaults/main.yaml file
# storing the Output of the resource created into a variable.
- block:
    - name: create a VPC resource
      ec2_vpc_net:
        aws_access_key: "{{ var_aws_access_key_id }}" 
        aws_secret_key: "{{ var_aws_secret_key_id }}"
        name: "{{ var_vpc_name }}"
        cidr_block: "{{var_vpc_cidr_block}}"
        region: "{{var_vpc_region}}"
        tags:
          "{{ var_vpc_tags }}"
        tenancy: "{{var_vpc_tenacy}}"
        state: "{{ var_vpc_state}}"
      register: var_resource_output
    
# Task to Display the output of the resource created into the console
    - name : display vpc resource info
      debug: msg="{{ var_resource_output }}"

# Assigning vpc id into a variable
    - name: create var_vpc_id variable and assign vpc_id to it
      set_fact:
        var_vpc_id: "{{var_resource_output.vpc.id}}"

# Display the vpc id into the console
    - name : display vpc id
      debug: msg="{{ var_vpc_id }}"

  rescue:

# Handling Error by displaying error message
    - name: Display Error message
      debug: msg="creating AWS VPC failed"

# Stopping the play for the current host
    - name: End the play for hosts
      meta: end_host



